name: Build and deploy ASP.Net Core app to an Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        IMAGE_NAME: 'sampleapi'
        TAG: ${{ github.sha }}
  
    steps:
      - uses: actions/checkout@v3

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ vars.DOCKER_LOGIN_SERVER }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_LOGIN_SERVER }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build with dotnet
        run: dotnet publish -c Release -t:PublishContainer -p ContainerRepository=${{ vars.DOCKER_LOGIN_SERVER }}/${{ env.IMAGE_NAME }} -p ContainerRegistry=${{ vars.DOCKER_LOGIN_SERVER }}
        working-directory: src/SampleApi